TOKEN_TRANSFER_PROGRAM_PUBKEY,TMONK_MINT_ADDRESS

export const TOKEN_TRANSFER_PROGRAM_PUBKEY = new PublicKey("8GuUDSZ8XiCxFL9cPjNeJdVedCx6JSsFknv6x2Mc41kV");

export const TMONK_MINT_ADDRESS = new PublicKey("8GuUDSZ8XiCxFL9cPjNeJdVedCx6JSsFknv6x2Mc41kV");